CORRECTIONS = {
    "can't've": "cannot have",
    "'cause": "because",
    "could've": "could have",
    "couldn't've": "could not have",
    "hadn't": "had not",
    "hadn't've": "had not have",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'd've": "he would have",
    "he'll": "he will",
    "how'd": "how did",
    "how'll": "how will",
    "i'd": "i would",
    "it'd": "it would",
    "ma'am": "madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "must've": "must have",
    "mustn't": "must not",
    "needn't": "need not",
    "oughtn't": "ought not",
    "shan't": "shall not",
    "sha'n't": "shall not",
    "she'd": "she would",
    "she'll": "she will",
    "should've": "should have",
    "that'd": "that would",
    "there'd": "there had",
    "they'd": "they would",
    "they'll": "they will",
    "they're": "they are",
    "they've": "they have",
    "we'd": "we would",
    "we'll": "we will",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what will",
    "what're": "what are",
    "what've": "what have",
    "where'd": "where did",
    "where's": "where is",
    "who'll": "who will",
    "who's": "who is",
    "you'd": "you would",
    'nvr': 'never',
    'uhh': 'you',
    'uh': 'you',
    'phn': 'phone',
    'jst ': 'just',
    'cz': 'because',
    'aint': 'am not',
    'nw': 'now',
    'srry': 'sorry',
    'pic': 'picture',
    'snd': 'send',
    'ppls': 'please',
    'whn': 'when',
    'nthing': 'nothing',
    'samting': 'somthing',
    'dnot': 'do not',
    'thankyou': 'thank you',
    'frnd': 'friend',
    'qstn': 'question',
    "nthng": 'nothing',
    "whatsup": 'what is up',
    'thnxx': 'thanks',
    'thnx': 'thanks',
    "hppnd": 'happend',
    "isfor": 'is for',
    "wasn't": 'was not',
    'havent': 'have not',
    "replyme": 'reply me',
    "iscomputer": 'is computer',
    "whatsapp": 'what is application',
    'didnt': "did not",
    "thanx": 'thanks',
    "you've": 'you have',
    "ain't": 'can not',
    'nufn': 'nothing',
    "&": 'and',
    "dn": 'do not',
    "nd": 'end',
    "doesn't": 'dose not',
    "aren't": 'are not',
    'wont': 'will not',
    'isnt': 'is not',
    'wht': 'what',
    "ur's": 'your is',
    'tme': 'time',
    'slp': 'sleep',
    'tym': 'time',
    'wat': 'what',
    'hv': 'have',
    'ntng': 'nothing',
    "we're": 'we are',
    "plzz": 'please',
    "arn't": 'are not',
    'arnt': 'are not',
    'wouldnt': 'would not',
    "wouldn't": 'would not',
    'shouldnt': 'should not',
    "shouldn't": 'should not',
    "couldn't": 'could not',
    "couldnt": 'could not',
    "it'll": "it will",
    "itll": 'it will',
    "whats": 'what is',
    "she's": 'she is',
    'shes': 'she is',
    "he's": 'he is',
    'hes': 'he is',
    "how's": 'how is',
    'hows': 'how is',
    "nt": 'nothing',
    "isn't": 'is not',
    "dont": "do not",
    "when's": 'when is',
    'whens': 'when is',
    "there's": 'there is',
    'its': 'it is',
    "can't": "can not",
    "let's": 'let us',
    'lets': 'let us',
    "i've": 'i have',
    'ive': 'i have',
    "that's": 'that is',
    'thats': 'that is',
    "won't": 'will not',
    "what's": 'what is',
    "dosen't": 'dose not',
    'dosent': 'dose not',
    "you're": 'you are',
    'youre': 'you are',
    "didn't": 'did not',
    "i'll": 'i will',
    "you'll": 'you will',
    "youll": 'you will',
    "it's": 'it is',
    "don't": 'do not',
    "i'm": 'i am',
    'dnt': 'do not',
    'frnds': 'friends',
    'bday': 'birthday',
    'wr': 'where',
    'wt': 'what',
    'wtf': 'What the fuck',
    'pl': 'please',
    'hw': 'how',
    'coz': 'because',
    'bcz': 'because',
    'cuz': 'cause',
    'Idk': 'i do not know',
    'idk': 'i do not know',
    'bt': 'but',
    'abt': 'about',
    'bcoz': 'because',
    'im': 'i am',
    'U': 'you',
    'r': 'are',
    'R': 'are',
    'gf': 'girlfriend',
    'bf': 'boyfriend',
    'Ur': 'Your',
    'wlcm': 'Wellcome',
    'm8': 'mate',
    'mgmt': 'management',
    'mmfu': 'my mate fancies you',
    'mob': 'mobile',
    'msg': 'message ',
    'msia': 'malaysia',
    'mtfbwu': 'may the force be with you',
    'mtg': 'meeting',
    'mth': 'month',
    'myob': 'mind your own business',
    'n/a': 'not applicable',
    'ne': 'any',
    'ne1': 'anyone',
    'nethng': 'anything',
    'no1': 'no one',
    'np': 'no problem',
    'nvm': 'never mind',
    'oic': 'oh, i see',
    'omg': 'oh, my god',
    'paw': 'parents are watching',
    'pcm': 'please call me',
    'pls': 'please',
    'plz': 'please',
    'plz4gvme': 'please forgive me',
    'po$bl': 'possible',
    'ppl': 'people',
    'prl': 'parents are listening',
    'puks': 'pick up kids',
    'rgds': 'regards',
    'ringl8': 'running late',
    'rtfm': 'read the flippin manual',
    'ru': 'are you',
    'cmng': 'coming',
    'ruok': 'are you okay?',
    'shopn': 'shopping',
    'sit': 'stay in touch',
    'soz': 'sorry',
    'spk': 'speak',
    'stfu': 'shut the flip up',
    'sum1': 'someone',
    'tel': 'telephone',
    'thanq': 'thank you',
    'thkq': 'thank you',
    'thx': 'thanks',
    'tmb': 'text me back',
    'tq': 'thank you',
    'ttyl': 'talk to you later',
    'tx': 'thanks',
    'tyvm': 'thank you very much',
    'u': 'you',
    'ur': 'your',
    'ura*': 'you are a star',
    'uraqt': 'you are a cutie',
    'w/': 'with',
    'w/o': 'without',
    'w8': 'wait',
    'w84m': 'wait for me',
    'wan2': 'want to',
    'wan2tlk': 'want to talk?',
    'wbs': 'with',
    'wearing': 'a walkman',
    'wel': 'well',
    'wiv': 'write back soon',
    'wknd': 'weekend',
    'wot': 'what',
    'wru': 'where are you?',
    'wu': "what's up?",
    'wud?': 'what you doing',
    'wygowm': 'will you go out with me',
    'x': 'kiss',
    'xlnt': 'excellent',
    'xoxox': 'hugs and kisses',
    'y': 'why',
    'yr': 'your',
    'yyssw': 'yeah yeah sure sure whatever',
    '1ce': 'once',
    '2': 'to',
    '26y4u': 'too sexy for you',
    '2day': 'today',
    '2mor': 'tomorrow',
    '2nite': 'tonight',
    '3sum': 'threesome',
    '4': 'for',
    '911': 'emergency - call me',
    'aka': 'also known as',
    'asap': 'as soon as possible',
    'atb': 'all the best',
    'b': 'be',
    'b4': 'before',
    'b4n': 'or bfn bye for now',
    'bbl': 'be back later',
    'bcnu': 'be seeing you',
    "b'day": 'birthday',
    'bhl8': 'be home late',
    'bil': 'boss is listening',
    'brb': 'be right back',
    'btdt': 'been there done that',
    'btw': 'by the way',
    'buzz': 'off buzz off',
    'c': 'see',
    'cid': 'consider it done',
    'cmi': 'call me',
    'ctr': 'center',
    'cu': 'see you',
    'cubl8r': 'call you back later',
    'cul': 'see you later',
    'cyr': 'call your',
    'bos': 'boss',
    'bro': 'brother',
    'ma': 'mother',
    'ofis': 'office',
    'pa': 'father',
    'wf': 'wife',
    'don': 'doing',
    'dylm': 'do you like me',
    'ez': 'easy',
    'f2f': 'face to face',
    'f2t': 'free to talk',
    'fotflol': 'falling on the floor, laughing out loud',
    'fyi': 'for your in from ation',
    'gal': 'get a life',
    'grt': 'great',
    'gtg': 'got to go',
    'gudluk': 'good luck',
    'h8': 'hate',
    'hak': 'hugs and kisses',
    'hand': 'have a nice day',
    'hot4u': 'hot for you',
    'hp': 'handphone',
    'ic': 'i see',
    'iluvu': 'i love you',
    'im2gud4u': "i'm too good for you",
    'imho': 'in my humble opinion',
    'imnsho': 'in my not so humble opinion',
    'imtng': 'in meeting',
    'iyq': 'i like you',
    'jhb': 'johannesburg',
    'jic': 'just in case',
    'jk': 'just kdding',
    'kit': 'keep in touch',
    'kwim': 'know what i mean',
    'l8': 'late',
    'l8r': 'later',
    'ldn': 'london',
    'lol': 'laughing out loud or loads of love',
    'lv': 'love',
    'lying': 'lyn'
}

EMOTICONS_TOKEN = {
    '>_>': '<doubt>',
    '-_-': '<indifference>',
    '(^_^)': '<smile>',
    ':*': '<kiss>',
    ':-*': '<kiss>',
    ':x': '<kiss>',
    ':-)': '<happy>',
    ':-))': '<happy>',
    ':-)))': '<happy>',
    ':-))))': '<happy>',
    ':-)))))': '<happy>',
    ':-))))))': '<happy>',
    ':)': '<happy>',
    ':))': '<happy>',
    ':)))': '<happy>',
    ':))))': '<happy>',
    ':)))))': '<happy>',
    ':))))))': '<happy>',
    ':)))))))': '<happy>',
    ':o)': '<happy>',
    ':]': '<happy>',
    ':3': '<happy>',
    ':c)': '<happy>',
    ':>': '<happy>',
    '=]': '<happy>',
    '8)': '<happy>',
    '=)': '<happy>',
    ':}': '<happy>',
    ':^)': '<happy>',
    '|;-)': '<happy>',
    ":'-)": '<happy>',
    ":')": '<happy>',
    '\o/': '<happy>',
    '*\\0/*': '<happy>',
    ':-D': '<laugh>',
    ':D': '<laugh>',
    # '(\':': '<laugh>',
    '8-D': '<laugh>',
    '8D': '<laugh>',
    'x-D': '<laugh>',
    'xD': '<laugh>',
    'X-D': '<laugh>',
    'XD': '<laugh>',
    '=-D': '<laugh>',
    '=D': '<laugh>',
    '=-3': '<laugh>',
    '=3': '<laugh>',
    'B^D': '<laugh>',
    '>:[': '<sad>',
    ':-(': '<sad>',
    ':-((': '<sad>',
    ':-(((': '<sad>',
    ':-((((': '<sad>',
    ':-(((((': '<sad>',
    ':-((((((': '<sad>',
    ':-(((((((': '<sad>',
    ':(': '<sad>',
    ':((': '<sad>',
    ':(((': '<sad>',
    ':((((': '<sad>',
    ':(((((': '<sad>',
    ':((((((': '<sad>',
    ':(((((((': '<sad>',
    ':((((((((': '<sad>',
    ':-c': '<sad>',
    ':c': '<sad>',
    ':-<': '<sad>',
    ':<': '<sad>',
    ':-[': '<sad>',
    ':[': '<sad>',
    ':{': '<sad>',
    ':-||': '<sad>',
    ':@': '<sad>',
    ":'-(": '<sad>',
    ":'(": '<sad>',
    'D:<': '<sad>',
    'D:': '<sad>',
    'D8': '<sad>',
    'D;': '<sad>',
    'D=': '<sad>',
    'DX': '<sad>',
    'v.v': '<sad>',
    "D-':": '<sad>',
    '(>_<)': '<sad>',
    ':|': '<sad>',
    '>:O': '<surprise>',
    ':-O': '<surprise>',
    ':-o': '<surprise>',
    ':O': '<surprise>',
    '°o°': '<surprise>',
    'o_O': '<surprise>',
    'o_0': '<surprise>',
    'o.O': '<surprise>',
    'o-o': '<surprise>',
    '8-0': '<surprise>',
    '|-O': '<surprise>',
    ';-)': '<wink>',
    ';)': '<wink>',
    '*-)': '<wink>',
    '*)': '<wink>',
    ';-]': '<wink>',
    ';]': '<wink>',
    ';D': '<wink>',
    ';^)': '<wink>',
    ':-,': '<wink>',
    '>:P': '<tong>',
    ':-P': '<tong>',
    ':P': '<tong>',
    'X-P': '<tong>',
    'x-p': '<tong>',
    'xp': '<tong>',
    'XP': '<tong>',
    ':-p': '<tong>',
    ':p': '<tong>',
    '=p': '<tong>',
    ':-Þ': '<tong>',
    ':Þ': '<tong>',
    ':-b': '<tong>',
    ':b': '<tong>',
    ':-&': '<tong>',
    '>:\\': '<annoyed>',
    '>:/': '<annoyed>',
    ':-/': '<annoyed>',
    ':-.': '<annoyed>',
    ':/': '<annoyed>',
    ':\\': '<annoyed>',
    '=/': '<annoyed>',
    '=\\': '<annoyed>',
    ':L': '<annoyed>',
    '=L': '<annoyed>',
    ':S': '<annoyed>',
    '>.<': '<annoyed>',
    ':-|': '<annoyed>',
    '<:-|': '<annoyed>',
    '>:(': '<annoyed>',
    ":-\\": '<anger>',
    ':-X': '<seallips>',
    ':X': '<seallips>',
    ':-#': '<seallips>',
    ':#': '<seallips>',
    'O:-)': '<angel>',
    '0:-3': '<angel>',
    '0:3': '<angel>',
    '0:-)': '<angel>',
    '0:)': '<angel>',
    '0;^)': '<angel>',
    '>:)': '<devil>',
    '>:D': '<devil>',
    '>:-D': '<devil>',
    '>;)': '<devil>',
    '>:-)': '<devil>',
    '}:-)': '<devil>',
    '}:)': '<devil>',
    '3:-)': '<devil>',
    '3:)': '<devil>',
    'o/\o': '<highfive>',
    '^5': '<highfive>',
    '>_>^': '<highfive>',
    '^<_<': '<highfive>',
    '<3': '<heart>',
    '^-^': '<smile>',
    '(^ . ^)': '<happy>',
    '(:': '<happy>',
    '(^○^)': '<lovely>',
}

EMOTICONS_UNICODE = {
    '😀': '<Grinning_Face>', '😃': '<Smiling_Face_With_Open_Mouth>',
    '😄': '<Smiling_Face_With_Open_Mouth_And_Smiling_Eyes>', '😁': '<Grinning_Face_With_Smiling_Eyes>',
    '😆': '<Smiling_Face_With_Open_Mouth_And_Closed_Eyes>', '😅': '<Smiling_Face_With_Open_Mouth_>',
    '😂': '<Face_With_Tears_of_Joy>', '🤣': '<Rolling_On_The_Floor>', '☺': '<Smiling_Face>',
    '😊': '<Smiling_Face_With_Smiling_Eyes>', '😇': '<Smiling_Face_With_Halo>', '🙂': '<Slightly_Smiling_Face>',
    '🙃': '<Upside-Down_Face>', '😉': '<Winking_Face>', '😌': '<Relieved_Face>', '😍': '<Smiling_Face_With_Heart-Eyes>',
    '\U0001f970': '<Smiling_face_with_smiling_eyes_and_three_hearts>', '😘': '<Face_Throwing_a_Kiss>',
    '😗': '<Kissing_Face>', '😙': '<Kissing_Face_With_Smiling_Eyes>', '😚': '<Kissing_Face_With_Closed_Eyes>',
    '😋': '<Face_Savouring_Delicious_Food>', '😛': '<Face_With_Stuck-Out_Tongue>',
    '😝': '<Face_With_Stuck-Out_Tongue_>', '😜': '<Face_With_Stuck-Out_Tongue_>', '\U0001f92a': '<Crazy_Face>',
    '\U0001f928': '<Face_With_a_Raised_Eyebrow>', '\U0001f9d0': '<Face_With_Monocle>', '🤓': '<Nerd_Face>',
    '😎': '<Face_With_Sunglasses>', '\U0001f929': '<Smirking_Face_With_Starry_Eyes>',
    '\U0001f973': '<Face_with_party_blower_and_party_hat>', '😏': '<Smirking>', '😒': '<Unamused_Face>',
    '😞': '<Disappointed_Face>', '😔': '<Pensive_Face>', '😟': '<Worried_Face>', '😕': '<Confused_Face>',
    '☹': '<Frowning_Face>', '😣': '<Suffering_Face>', '😖': '<Confounded_Face>', '😫': '<Tired_Face>',
    '😩': '<Weary_Face>', '\U0001f97a': '<Face_with_begging_eyes>', '😢': '<Crying_Face>', '😭': '<Loudly_Crying_Face>',
    '😤': '<Face_With_Look_of_Triumph>', '😠': '<Angry_Face>', '😡': '<Pouting_Face>',
    '\U0001f92c': '<Face_With_Symbols_Over_The_Mouth>', '\U0001f92f': '<Face_With_Exploding_Head>',
    '😳': '<Flushed_Face>', '\U0001f975': '<Overheated_face>', '\U0001f976': '<Freezing_face>',
    '😱': '<Face_Screaming_in_Fear>', '😨': '<Fearful_Face>', '😰': '<Face_With_Open_Mouth_>',
    '😥': '<Disappointed_but_Relieved_Face>', '😓': '<Face_With_Cold_Sweat>', '🤗': '<Hugging_Face>',
    '🤔': '<Thinking_Face>', '\U0001f92d': '<Face_With_Hand_Over_The_Mouth>', '\U0001f92b': '<Exhorting_Face>',
    '🤥': '<Lying_Face>', '😶': '<Face_Without_Mouth>', '😐': '<Neutral_Face>', '😑': '<Expressionless_Face>',
    '😬': '<Grimacing_Face>', '🙄': '<Face_With_Rolling_Eyes>', '😯': '<Speechless_Face>',
    '😦': '<Frowning_Face_With_Open_Mouth>', '😧': '<Anguished_Face>', '😮': '<Face_With_Open_Mouth>',
    '😲': '<Astonished_Face>', '😴': '<Sleeping_Face>', '🤤': '<Drooling_Face>', '😪': '<Sleepy_Face>',
    '😵': '<Dizzy_Face>', '🤐': '<Zipper-Mouth_Face>', '\U0001f974': '<Face_with_unequal_eyes_and_wavy_mouth>',
    '🤢': '<Nauseated_Face>', '\U0001f92e': '<Face_With_Open_Mouth>', '🤧': '<Sneezing_Face>',
    '😷': '<Face_With_Medical_Mask>', '🤒': '<Face_With_Thermometer>', '🤕': '<Face_With_Head_Bandage>',
    '🤑': '<Money-Mouth_Face>', '🤠': '<Face_With_Cowboy_Hat>', '😈': '<Smiling_Face_With_Horns>', '👿': '<Goblin>',
    '👹': '<Japanese_Ogre_>', '👺': '<Japanese_Goblin>', '🤡': '<Clown_Face>', '💩': '<Pile_of_Poo>', '👻': '<Ghost>',
    '💀': '<Skull>', '☠': '<Skull_and_Crossbones>', '👽': '<Alien>', '🤖': '<Robot_Face>',
    '😺': '<Smiling_Cat_Face_With_Open_Mouth>', '😸': '<Grinning_Cat_Face_With_Smiling_Eyes>',
    '😹': '<Cat_Face_With_Tears_of_Joy>', '😻': '<Smiling_Cat_Face_With_Heart-Eyes>', '😼': '<Cat_Face_With_Wry_Smile>',
    '😽': '<Kissing_Cat_Face_With_Closed_Eyes>', '🙀': '<Weary_Cat_Face>', '😿': '<Crying_Cat_Face>',
    '😾': '<Pouting_Cat_Face>', '👐': '<Open_Hands>', '🙌': '<Person_Raising_Both_Hands_In_Celebration>',
    '👏': '<Clapping_Hands>', '👍': '<Thumbs-Up_Sign>', '👎': '<Thumbs_Down_Sign>', '👊': '<Fist_Hand>',
    '✊': '<Raised_Fist>', '🤛': '<Fist_Pointing_Left>', '🤜': '<Fist_Pointing_Right>',
    '🤞': '<Hand_With_Crossed_Fingers>', '✌': '<Victory_Hand>', '\U0001f91f': '<I_Love_You_Gesture>',
    '🤘': '<Sign_of_the_Horns>', '👌': '<Ok_Hand_Sign>', '👈': '<Back_Of_Hand_Pointing_To_The_Left>',
    '👉': '<Back_Of_Hand_Pointing_To_The_Right>', '👆': '<Back_Of_Hand_Pointing_Upwards>',
    '👇': '<Back_Of_Hand_Pointing_Downwards>', '☝': '<Up_Pointing_Index>', '✋': '<Raised_Hand>',
    '🤚': '<Raised_Back_of_Hand>', '🖐': '<Raised_Hand_With_Fingers_Splayed>', '🖖': '<Mr._Spock_Greeting>',
    '👋': '<Waving_Hand>', '🤙': '<Call_Me_Hand_Sign>', '💪': '<Tense_Biceps>',
    '🖕': '<Reversed_Hand_With_Middle_Finger_Extended>', '✍': '<Writing_Hand>', '🙏': '<Person_With_Folded_Hands>',
    '\U0001f9b6': '<Foot>', '\U0001f9b5': '<Leg>', '💍': '<Ring>', '💄': '<Lipstick>', '💋': '<Kiss_Mark>',
    '👄': '<Mouth>', '\U0001f9b7': '<Tooth>', '👅': '<Tongue>', '👂': '<Ear>', '👃': '<Nose>', '👣': '<Footprints>',
    '👁': '<Eye>', '👀': '<Eyes>', '\U0001f9e0': '<Brain>', '\U0001f9b4': '<Bone>', '🗣': '<Talking_Head>',
    '👤': '<Silhouette_of_a_Bust>', '👥': '<Silhouette_Of_Two_Busts>', '👶': '<Baby>', '👧': '<Girl>', '👦': '<Boy>',
    '👩': '<Woman>', '👨': '<Man>', '👵': '<Elderly_Woman>', '👴': '<Old_Man>', '👮': '<Policeman>', '👷': '<Builder>',
    '🕵': '<Detective>', '👰': '<Bride>', '👸': '<Princess>', '\U0001f9b8': '<Superhero>',
    '\U0001f9b9': '<Super_villain>', '🎅': '<Santa_Claus>', '\U0001f9dc': '<Mermaid>', '👼': '<Baby_Angel>',
    '🙇': '<Person_Bowing_Deeply>', '💁': '<Information_Desk_Person>', '🙅': '<Face_With_No_Good_Gesture>',
    '🙆': '<Face_With_Ok_Gesture>', '🙋': '<Happy_Person_Raising_One_Hand>', '🤦': '<Man_Grabbing_His_Head>',
    '🤷': '<Person_Shrugs>', '🙎': '<Pouting_Person>', '🙍': '<Frowning_Person>',
    '\U0001f9d6': '<Person_in_Steam_Sauna>', '💅': '<Nail_Polish>', '💃': '<Dancing>', '🕺': '<Dancing_Man>',
    '👯': '<Women_With_Bunny_Ears>', '🕴': '<Hovering_Man_in_Suit>', '🚶': '<Pedestrian>', '🏃': '<Runner>',
    '👫': '<Man_and_Woman_Holding_Hands>', '👭': '<Two_Women_Holding_Hands>', '👬': '<Two_Men_Holding_Hands>',
    '💑': '<Couple_With_Heart>', '💏': '<Kiss>', '👪': '<Family>', '\U0001f9f6': '<Ball_of_wool>',
    '\U0001f9f5': '<Thread_reel>', '\U0001f97c': '<Laboratory_coat>', '👚': '<Woman>', '👕': '<T-Shirt>',
    '👖': '<Jeans>', '👔': '<Shirt_With_Tie>', '👗': '<Dress>', '👙': '<Bikini>', '👘': '<Kimono>',
    '\U0001f97f': '<Ballerina>', '👠': '<High-Heeled_Shoe>', '👡': '<Woman>', '👞': '<Man>',
    '\U0001f97e': '<Safety_glasses>', '🎩': '<Top_Hat>', '👒': '<Woman>', '🎓': '<Alumnus_Hat>', '⛑': '<Rescue_Worker>',
    '👑': '<Crown>', '👝': '<Clutch>', '\U0001f9f3': '<Suitcase>', '👓': '<Glasses>', '🕶': '<Dark_Sunglasses>',
    '☂': '<Open_Umbrella>', '❤': '<Red_Heart>', '\U0001f9e1': '<Orange_Heart>', '💛': '<Yellow_Heart>',
    '💚': '<Green_Heart>', '💙': '<Blue_Heart>', '💜': '<Purple_Heart>', '🖤': '<Black_Heart>', '💔': '<Broken_Heart>',
    '❣': '<Heavy_Heart_Exclamation_Mark_Ornament>', '💕': '<Two_Hearts>', '💞': '<Revolving_Hearts>',
    '💓': '<Beating_Heart>', '💗': '<Growing_Heart>', '💖': '<Sparkling_Heart>', '💘': '<Heart_With_Arrow>',
    '💝': '<Heart_With_Ribbon>', '💟': '<Heart_Decoration>', '🕉': '<Om_Symbol>', '☸': '<Wheel_Of_Dharma>',
    '✡': '<Star_Of_David>', '🔯': '<Hexagram_With_Dot>', '🕎': '<Menorah>', '☯': '<Yin_Yang>', '☦': '<Orthodox_Cross>',
    '🛐': '<Place_of_Worship>', '⛎': '<Ophiuchus>', '♓': '<Pisces>', '🆔': '<ID_Key>', '☣': '<Biohazard>',
    '📴': '<Mobile_Phone_Off>', '♈': '<Aries>', '♉': '<Taurus>', '♊': '<Gemini>', '♋': '<Cancer>', '♌': '<Leo>',
    '♍': '<Virgo>', '♎': '<Libra>', '♏': '<Scorpius>', '♐': '<Sagittarius>', '♑': '<Capricorn>', '♒': '<Aquarius>',
    '💮': '<White_Flower>', '🀄': '<Mahjong_Game_Stone_>', '🉑': '<Acceptable>', '📳': '<Vibration_Mode>',
    '🈶': '<Subject_To_Fees>', '🈚': '<Without_Fees>', '🈺': '<Open>', '🈸': '<Application>', '🈷': '<Monthly>',
    '✴': '<Eight-Pointed_Star>', '🆚': '<VS_Button>', '🉐': '<Bargain>', '㊙': '<Secret>', '㊗': '<Congratulations>',
    '🈴': '<Passed>', '🈵': '<Full>', '🈹': '<Discount>', '🈲': '<Prohibition>', '❌': '<Cross_Mark>',
    '🎏': '<Carp_Streamer>', '⛔': '<No_Entry>', '📛': '<Name_Badge>', '🚫': '<No_Admittance>', '💢': '<Anger_Symbol>',
    '♨': '<Hot_Springs>', '❓': '<Question_Mark_Ornament>', '❔': '<White_Question_Mark>', '❗': '<Exclamation_Mark>',
    '❕': '<White_Exclamation_Mark>', '‼': '<Double_Exclamation_Mark>', '💯': '<Hundred_Points_Symbol>',
    '🔱': '<Trident_Emblem>', '⚜': '<Fleur-De-Lis>', '〽': '<Part_Alternation_Mark>', '⚠': '<Warning>',
    '🚸': '<Caution_Children>', '♻': '<Recycling_Symbol>', '🈯': '<Reserved>', '🌐': '<Globe_With_Meridians>',
    '💠': '<Diamond_Shape_With_a_Dot_Inside>', '🌀': '<Cyclone>', '🚾': '<Water_Closet>', '🈳': '<Vacancy>',
    '🈂': '<Free_Of_Charge>', '🛅': '<Baggage_Room>', '🚹': '<Men_symbol>', '🚺': '<Ladies>', '🚼': '<Baby>',
    '🎦': '<Cinema>', '🔣': '<Input_Symbol>', '🆖': '<NG_Button>', '0': '<Zero_Key>', '1': '<One_Key>',
    '2': '<Two_Key>', '4': '<Four_Key>', '7': '<Seven_Key>', '⃣': '<Keycap_Number_Sign>', '🔽': '<Downward_Button>',
    '➡': '<Right_Arrow>', '⬅': '<Left_Arrow>', '⬆': '<Up_Arrow>', '🔄': '<Anticlockwise_Open_Circle_Arrows>',
    '🎵': '<Note>', '〰': '<Wavy_Dash>', '➰': '<Curly_Loop>', '➿': '<Double_Curly_Loop>',
    '✖': '<Heavy_Multiplication_X>', '♾': '<Infinity>', '🔚': '<END_With_Left_Arrow_Above>',
    '🔙': '<BACK_With_Left_Arrow>', '🔝': '<Top_Arrow>', '🔜': '<Soon_Arrow>', '✔': '<Bold_Tick>',
    '🔘': '<Radio_Button>', '⚪': '<White_Circle>', '⚫': '<Black_Circle>', '🔴': '<Large_Red_Circle>',
    '🔸': '<Small_orange_diamond>', '🔹': '<Small_Blue_Diamond>', '🔳': '<White_Square_Key>',
    '◼': '<Black_Medium_Square>', '💱': '<Eye_in_Speech_Bubble>', '™': '<Currency_Exchange>',
    '©': '<Registered_Trademark>', '®': '<Copyright_Symbol>', '💭': '<Registered_Logo>', '💬': '<Thought_Balloon>',
    '♠': '<Speech_Balloon>', '♥': '<Spade_Suit>', '📱': '<Hearts_Playing_Card>', '📲': '<Mobile_Phone>',
    '💻': '<Mobile_Phone_With_Rightwards_Arrow_at_Left>', '🖥': '<Laptop>', '🖱': '<Desktop_Computer>',
    '🖲': '<Computer_Mouse>', '🕹': '<Trackball>', '🗜': '<Joystick>', '📼': '<Compression>', '📸': '<Video_Cassette>',
    '📞': '<Camera_With_Flash>', '\U0001f9ed': '<Earphone>', '⏰': '<Compass>', '⏳': '<Alarm_Clock>',
    '🔩': '<Hourglass_With_Flowing_Sand>', '⚙': '<Bolt_And_Nut>', '\U0001f9f1': '<Gear>', '💡': '<Brick>',
    '🔦': '<Electric_Light_Bulb>', '\U0001f9ef': '<Flashlight>', '💸': '<Fire_extinguisher>',
    '💶': '<Money_With_Wings>', '💎': '<Euro_Banknote>', '\U0001f9f0': '<Gem_Stone>', '🔫': '<Tool_box>',
    '💰': '<Pistol>', '⛓': '<Moneybag>', '\U0001f9f2': '<Chain>', '\U0001f9e8': '<Magnet>', '💣': '<Fireworks>',
    '🔪': '<Bomb>', '🛡': '<Japanese_Kitchen_Knife>', '🚬': '<Shield>', '⚰': '<Cigarette>', '🔮': '<Coffin>',
    '📿': '<Crystal_Ball>', '\U0001f9ff': '<Prayer_Beads>', '⚗': '<Nazar_amulet>', '🕳': '<Alembic>', '💊': '<Hole>',
    '💉': '<Pill>', '\U0001f9a0': '<Syringe>', '\U0001f9ec': '<Microbe>', '\U0001f9eb': '<DNA_double_helix>',
    '\U0001f9ea': '<Petri_dish>', '\U0001f9f9': '<Test_tube>', '\U0001f9fa': '<Broom>', '\U0001f9fb': '<Basket>',
    '🚽': '<Paper_roll>', '\U0001f9fc': '<Toilet>', '\U0001f9fd': '<Bar_of_soap>', '\U0001f9f4': '<Sponge>',
    '🔑': '<Lotion_bottle>', '🗝': '<Key>', '🛏': '<Antique_Key>', '\U0001f9f8': '<Bed>', '🖼': '<Teddy_bear>',
    '🛍': '<Framed_Picture>', '🔖': '<Shopping_bags>', '🗿': '<Bookmark>', '🎈': '<Moai>', '🏮': '<Balloon>',
    '🎀': '<Izakaya_Paper_Lantern>', '🎊': '<Ribbon>', '🎉': '<Confetti_Ball>', '🎎': '<Party_Popper>',
    '🎐': '<Japanese_Dolls>', '\U0001f9e7': '<Wind_Chime>', '✉': '<Red_gift_envelope>', '💌': '<Envelope>',
    '🏷': '<Love_Letter>', '\U0001f9fe': '<Label>', '📊': '<Sales_receipt>', '📈': '<Bar_Chart>',
    '\U0001f9f7': '<Chart_With_Uptrend>', '\U0001f9ee': '<Safety_pin>', '📍': '<Abacus>', '🎌': '<Round_Pushpin>',
    '🔏': '<Crossed_Flags>', '🔓': '<Lock_With_Ink_Pen>', '🔒': '<Open_Lock>', '🔐': '<Lock>',
    '🏻': '<Light_Skin_Tone>', '🐺': '<Wolf_Face>', '🙁': '<Slightly_Frowning_Face>', '🏼': '<Medium-Light_Skin_Tone>',
    '⏸': '<Pause_Button>', '🌍': '<Globe_Showing_Europe-Africa>', '🏕': '<Camping>', '🎁': '<Wrapped_Gift>',
    '🍼': 'Baby_Bottle', '🍓': '<Strawberry>', '∑': '<Summation>', '🏾': '<Medium-Dark_Skin_Tone>',
    '🙊': '<Monkey_Covering_Mouth>', '🙈': '<Monkey_Covering_Eyes>', '🏿': '<Dark_Skin_Tone>',
    '⏪': '<Fast_Reverse_Button>', '💵': '<Dollar_Banknote>', '☎': '<Telephone>', '🎃': '<Pumpkin>', '🍒': '<Cherries>',
    '✨': '<Sparkles>', '🙉': '<Monkey_Covering_Ears>', '♀': '<Female_Sign>', '♂': '<Male_Sign>',
    '♡': '<White_Heart_Suit>', '🏽': '<Medium_Skin_Tone>', '🐱': '<Cat_Face>', '🐠': '<Tropical_Fish>',
    '⚽': '<Soccer_Ball>', '🐒': '<Monkey>', '🏖': '<Beach_With_Umbrella>', '🐘': '<Elephant>',
    '📆': '<Tear-Off_Calendar>', '⁉': '<Exclamation_Question_Mark>', '🔥': '<Fire>', '🌷': '<Tulip>', '🌹': '<Rose>',
    '⚘': '<Flower>', '🎧': '<Headphone>', '🏣': '<Japan_Post>', '🐇': '<Rabbit>', '🐰': '<Rabbit_Face>',
    '☕': '<Coffee>', '✈': '<Airplane>', '🖑': '<Reversed_Raised_Hand_with_Fingers_Splayed>', '💤': '<Sleepy>',
    '★': '<Black_Star>', '🚘': '<Car>', '🚗': '<Car>', '🐼': '<Panda_Face>', '🐻': '<Bear_Face>',
    '🎂': '<Birthday_Cake>', '💐': '<Bouquet>', '☔': '<Raining>', '🐷': '<Pig_Face>'
}
